WIP Add last updated timestamp to biography
DemocracyClub/yournextrepresentative pull request #2182
Opened 2023-09-26 10:21 UTC by VirginiaDooley

```[tasklist]
### PR Checklist
- [ ] References a specific issue or if not, describes the bug or feature in detail
- [ ] Note what card in Trello this work relates to
- [ ] Instructions for how reviewers can test the code locally
- [ ] Tests have been added and/or updated
- [ ] Screenshot of the feature/bug fix (if applicable)
- [ ] If any new text is added, it's internationalized
- [ ] Any new elements have aria labels
- [ ] No unintentional console.logs left behind after debugging
- [ ] Did I use the clear and concise names for variables and functions?
- [ ] Did I explain all possible solutions and why I chose the one I did?
- [ ] Added any comments to make new functions clearer
- [ ] Did I added or updated any new dependencies? Explain why.
- [ ] Did I update the package.json and/or Pipfile.lock version if relevant?
- [ ] Have I rebased with the latest version of master?
- [ ] Added PR labels
- [ ] Update any history/changelog file
- [ ] Update any documentation
- [ ] Update dev handbook
```

2023-10-02 17:48 UTC, VirginiaDooley commented
This seems to be using a time that is an hour behind the current time zone.

2023-10-04 12:55 UTC, symroe commented
Not sure but the test failure might be because of the date formatting in the templates. I think if you add a date in a template it will format it automatically, is this what you see on the page?

Also, can you add the migration to populate the timestamps?

2023-10-05 09:43 UTC, symroe commented
> should I have kept the first to reference in the migration?

I think you can just write it into the migration file. [This migration](https://github.com/DemocracyClub/yournextrepresentative/blob/493d6e15e9903489c124800a2675c71b885eed1c/ynr/apps/people/migrations/0021_populate_json_versions.py) might be a good starting point?

For the date, you can use `django.template.defaultfilters.date` in the test to format the date in the same way as the template does.

2023-10-05 16:40 UTC, VirginiaDooley commented
> 04f2f5d

Done with https://github.com/DemocracyClub/yournextrepresentative/pull/2182/commits/04f2f5d5c08c84f15fadcf0553a7dee81e841c4f

2023-10-11 10:27 UTC, Bekabyx commented
Local testing:

When I add a statement to voters to a candidate I get the following errors:
`TypeError at /person/59290/update
post_message() got an unexpected keyword argument 'text'`

Despite the error it does still write to the database. This error affects both candidates who haven't previously had a statement to voters and candidates that have.

Once the data is written, I can see it properly in the profile and the API.

2023-10-12 13:13 UTC, Bekabyx approved these changes
All the back and forth seems to have paid off - the migrations are working as expected now! 🎉

2023-10-12 13:22 UTC, symroe requested changes

2023-10-12 13:22 UTC, symroe commented on ynr/apps/people/migrations/0044_populate_biography_timestamp.py
> +                        person.save()
I think you need to return / break the loop here, otherwise the final version will be the date of the first edit to a statement

2023-10-12 13:39 UTC, symroe requested changes

2023-10-12 13:39 UTC, symroe commented on ynr/apps/people/migrations/0044_populate_biography_timestamp.py
> +                    if diff["data"]["biography"]:
I get loads of key errors on biography when I run this. If you changed this line to `diff["data"].get("biography")` most of them would go away I think

2023-10-12 13:39 UTC, symroe commented on ynr/apps/people/migrations/0044_populate_biography_timestamp.py
> +                    if diff["data"]["biography"]:
Actually, I think there's another change:

If there's not biography in the latest version (or set on the person model), then we don't need to check the previous versions: there's no biography.

I think we can wrap this in a `if person.biography` line, and then loop through versions to find the most recent edit to it. 

At the moment we're looping through all versions of all people even if they don't have a current statement. 

You could speed this up more by filtering the QS on `.exclude(biography="")` too.

2023-10-12 13:39 UTC, symroe commented on ynr/apps/people/migrations/0044_populate_biography_timestamp.py
> +                        person.biography_last_updated = diff["timestamp"]
Can you call [`make_aware`](https://docs.djangoproject.com/en/4.2/ref/utils/#django.utils.timezone.make_aware) on `diff["timestamp"]` please?

2023-10-16 10:43 UTC, symroe commented
Couple of things: 

1. You can remove the `if` statement from the loop (we know they all have a statement)
2. You need to parse the date before calling `make_aware`. 

This diff seems to work:

```diff
diff --git ynr/apps/people/migrations/0044_populate_biography_timestamp.py ynr/apps/people/migrations/0044_populate_biography_timestamp.py
index cdaa6002..2c99aac2 100644
--- ynr/apps/people/migrations/0044_populate_biography_timestamp.py
+++ ynr/apps/people/migrations/0044_populate_biography_timestamp.py
@@ -1,3 +1,5 @@
+from dateutil.parser import parse
+
 from candidates.diffs import get_version_diffs
 from django.db import migrations
 from django.utils.timezone import make_aware
@@ -6,22 +8,21 @@ from django.utils.timezone import make_aware
 def populate_biography_last_updated_timestamp(apps, schema_editor):
     Person = apps.get_model("people", "Person")
     for person in Person.objects.all().exclude(biography=""):
-        if person.biography:
-            try:
-                diffs = get_version_diffs(person.versions)
-                if diffs:
-                    for diff in diffs:
-                        if diff["data"].get("biography"):
-                            person.biography_last_updated = make_aware(
-                                diff["timestamp"]
-                            )
-                            person.save()
-                            break
-                else:
-                    person.biography_last_updated = person.created
-                    person.save()
-            except Exception as e:
-                print(f"Error on {person.pk}: {e}")
+        try:
+            diffs = get_version_diffs(person.versions)
+            if diffs:
+                for diff in diffs:
+                    if diff["data"].get("biography"):
+                        person.biography_last_updated = make_aware(
+                            parse(diff["timestamp"])
+                        )
+                        person.save()
+                        break
+            else:
+                person.biography_last_updated = person.created
+                person.save()
+        except Exception as e:
+            print(f"Error on {person.pk}: {e}")
 
 
 class Migration(migrations.Migration):
```

2023-10-16 14:17 UTC, symroe approved these changes

2023-10-16 14:19 UTC, merged